### PR TITLE
Re-enable CI using Github Actions

### PR DESCRIPTION
**Pull request by jjrodrig**
I plan to start to submit some PRs that aim to take control of the build system and artifacts publication. Do you think that this repo could be a new home (at least temporary) for the project?

This first PR  reenables the CI using GH Actions as the original Travis CI is not working. I've included some parts of IBM's internal CI based on Jenkins. 

Two workflows have been defined:
- A push and PR triggered workflow that builds and test the lib with 3 CouchDB versions 1.7.2, 2.31 and 3.2.1
- A manually triggered workflow that launches the tests on an Android Emulator

Thanks!

### CODE REVIEW

**Comment by janl** [comment]
sounds great, sorry for the delay here!

**Comment by geraldapeoples** [comment]
I'm so happy to see that mobile sync for couchdb is not dead, can't believe that cloudant have abandoned this, couchbase is growing exponentially due to mobile sync and IOT sync, there needs to be a genuine open source option and couchdb is brilliant. How do I get involved?

**Comment by jjrodrig** [comment]
Thanks @janl, first run failed... lets see if the next runs are ok. 

Next step is to publish this fork artifacts, we are looking for the best option for this. 

@geraldapeoples, any help will be great. Initially, we plan to modernize the build system and deps

**Comment by geraldapeoples** [comment]
I have a cordova plugin for couchbase that I maintain, so have some expertise with that side of things. Would it help if I was to maintain a couchdb plugin for cordova?

**Pull request merged**
